import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';
const result = await build({entryPoints:['vendor/thinking-orbs/browser.ts'], bundle:true, minify:true, write:false, format:'iife', target:'es2022', legalComments:'inline'});
await writeFile('src/report/thinkingOrbBundle.ts', '// Generated by npm run build:orbs. MIT © 2026 Jakub Antalik; see vendor/thinking-orbs/LICENSE.\nexport const THINKING_ORB_JS = ' + JSON.stringify(result.outputFiles[0].text) + ';\n');
